### ISSUE TITLE
[Question] Expiration Policy

### ISSUE THREAD

**Issue by Kikobeats** [ungoldman/nano-s3#4]
Hello,

This library is tiny and elegant, thanks for that!

I'm considering using it since I just need to upload S3 files.

For my use case, I can delete the file after N days. Let say, after 31 days.

For doing that, I was thinking just to use S3 [lifecycle hook](https://stackoverflow.com/questions/25791690/setting-s3-object-expiration-for-deletion-with-the-javascript-api).

But reading your code, now I have doubts related with expiration policy:
https://github.com/ungoldman/nano-s3/blob/master/index.js#L56

There you are setting up a value of 5 years. What's the purpose of this value? Should we, in my case, set a value of 31 days there?

Thanks for all 🙂

**Comment by ungoldman** [comment]
Hi @Kikobeats, it's been a while and the S3 interface is a bit arcane, but if memory serves me the _Policy Expiration_ refers to when this upload policy will expire.

If you look a little below the line you linked to, someone even left a helpful comment :)
```
  // Policy for uploading -- this is the restrictions we give to the upload form
  // and then sign so that we can detect if someone has tampered with it.
  // This is a mildly restrictive policy -- we cap the upload at 2MB unless overridden.
  // The date is five years in the future -- you will need to generate a new policy
  // and upload a new version of this file before this date and time!
  // Everything consumes the policy in a base64 format, but we need to make it
  // into a JSON string first.
```

So the line you linked to is not related to object expiration, but instead to policy expiration.

The stackoverflow thread you linked to seems to indicate that lifecycle configuration is managed through a variety of other endpoints and methods. Since this module is strictly for uploading a file to a S3 bucket that has _already been configured_, I think adding methods and options to configure lifecycles and object expirations is well out of the scope of this project. A quick read of the S3 docs linked to in the stackoverflow thread seems to me to indicate that this is something you can configure once, and not on each upload.

Best of luck!

**Comment by Kikobeats** [comment]
It clarified a lot, thanks for that 🙂

Are you using the library nowadays? I suppose s3 doesn't change too much these days

**Comment by ungoldman** [comment]
@Kikobeats yep, still using it in production. Haven't had to update it since I added it last year. S3/AWS interfaces are pretty stable and strictly versioned, so unless they deprecate this one it shouldn't need a change for a long while.
