### ISSUE TITLE
[Question] S3 Prefix optimization

### ISSUE THREAD

**Issue by Kikobeats** [ungoldman/nano-s3#5]
Hello,

This is another random question for trying to understand AWS S3 Documentation 😄 Since you created this library, _maybe_ you know the answer. Otherwise, feel free to close this!

Looks like S3 operations has a rate limit associated based on the file path:
https://docs.aws.amazon.com/AmazonS3/latest/dev/optimizing-performance.html

Based on [this reply at StackOverflow](https://stackoverflow.com/a/56155997), I understand rate limit is associated per prefix, so creating a new prefix just avoid run rate limit in the root of the bucket.

So, for example, if the filename is:

```
cL4CMUrbRYXA_z_EiVO9Osa758M_
```

Then we can create the following absolute path:

```
cL4CMUrbRYXA_/_EiVO9Osa758M_
```

Make sense? 🤔

**Comment by ungoldman** [comment]
This is not a problem we've dealt with yet, as we are nowhere near needing to worry about going above `3,500 PUT/COPY/POST/DELETE and 5,500 GET/HEAD requests per second per prefix in a bucket`.

It seems like randomly generating a prefix (or folder, since that's what we're really talking about) for every file runs a little close to abusing the service's leniency on rate limiting -- you may want to consider using folders and subfolders for different types and categories of files you want to store, rather than just putting every single file in its own folder.

Good luck. 👋
